from urllib.parse import urlencode, parse_qsl
import json

querystring = {"operationName":"ExploreSections","locale":"en-CA","currency":"CAD","_cb":"1ciq9jc0366e9214d7m7g0ge8kic","variables":"{\"isInitialLoad\":true,\"hasLoggedIn\":false,\"cdnCacheSafe\":false,\"source\":\"EXPLORE\",\"exploreRequest\":{\"metadataOnly\":false,\"version\":\"1.8.3\",\"itemsPerGrid\":20,\"tabId\":\"home_tab\",\"refinementPaths\":[\"/homes\"],\"flexibleTripDates\":[\"april\",\"march\"],\"flexibleTripLengths\":[\"weekend_trip\"],\"datePickerType\":\"calendar\",\"placeId\":\"ChIJpTvG15DL1IkRd8S0KlBVNTI\",\"source\":\"structured_search_input_header\",\"searchType\":\"autocomplete_click\",\"federatedSearchSessionId\":\"d17845e8-a3bf-4ac3-b180-8aca31231d08\",\"itemsOffset\":60,\"sectionOffset\":4,\"query\":\"Toronto, ON\",\"cdnCacheSafe\":false,\"treatmentFlags\":[\"flex_destinations_june_2021_launch_web_treatment\",\"new_filter_bar_v2_fm_header\",\"merch_header_breakpoint_expansion_web\",\"flexible_dates_12_month_lead_time\",\"storefronts_nov23_2021_homepage_web_treatment\",\"lazy_load_flex_search_map_wide\",\"flexible_dates_options_extend_one_three_seven_days\",\"super_date_flexibility\",\"micro_flex_improvements\",\"micro_flex_show_by_default\",\"search_input_placeholder_phrases\",\"pets_fee_treatment\"],\"screenSize\":\"large\",\"isInitialLoad\":true,\"hasLoggedIn\":false},\"removeDuplicatedParams\":false}",
"extensions":"{\"persistedQuery\":{\"version\":1,\"sha256Hash\":\"9018729a46757ca5654222f9ee71ab11fa840e38d1ceabe7763fcb37719e5648\"}}"}
variables = "{\"isInitialLoad\":true,\"hasLoggedIn\":true,\"cdnCacheSafe\":false,\"source\":\"EXPLORE\",\"exploreRequest\":{\"metadataOnly\":false,\"version\":\"1.8.3\",\"itemsPerGrid\":20,\"placeId\":\"ChIJpTvG15DL1IkRd8S0KlBVNTI\",\"refinementPaths\":[\"/homes\"],\"searchType\":\"AUTOSUGGEST\",\"tabId\":\"home_tab\",\"flexibleTripLengths\":[\"weekend_trip\"],\"datePickerType\":\"calendar\",\"federatedSearchSessionId\":\"5ae20964-250a-43a3-8273-d6513d4d5278\",\"itemsOffset\":40,\"sectionOffset\":3,\"query\":\"Toronto, ON\",\"cdnCacheSafe\":false,\"treatmentFlags\":[\"flex_destinations_june_2021_launch_web_treatment\",\"new_filter_bar_v2_fm_header\",\"merch_header_breakpoint_expansion_web\",\"flexible_dates_12_month_lead_time\",\"storefronts_nov23_2021_homepage_web_treatment\",\"web_remove_duplicated_params_fields\",\"flexible_dates_options_extend_one_three_seven_days\",\"super_date_flexibility\",\"micro_flex_improvements\",\"micro_flex_show_by_default\",\"search_input_placeholder_phrases\",\"pets_fee_treatment\"],\"screenSize\":\"large\",\"isInitialLoad\":true,\"hasLoggedIn\":true},\"removeDuplicatedParams\":true}"

d = json.loads(variables)

print(d)
